# Generated by Django 5.1.6 on 2025-03-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('mesero', 'Mesero'), ('cliente', 'Cliente')], default='mesero', max_length=10),
        ),
    ]
