# Generated by Django 5.1.6 on 2025-03-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('mesero', 'Mesero'), ('cliente', 'Cliente'), ('jefe_cocina', 'Jefe de cocina'), ('admin', 'Administrador')], default='mesero', max_length=20),
        ),
    ]
